title: Chirasree Mandal
description: Software engineer, student teacher, and designer studying Computer Science at Berkeley.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
pronouns: she/her/hers
