title: Chirasree Mandal
logo: ./assets/img/chirasree.png
description: Developer, student teacher, and designer studying Computer Science at Berkeley.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
